### ISSUE TITLE
React & Kotlin/JS - Setting up

### ISSUE THREAD

**Issue by simonpweller** [kotlin-hands-on/hands-on#117]
I was wondering if it might be worth addressing the New Project -> Kotlin -> React Application option in IntelliJ in the setting up section of the React & Kotlin/JS hands on. 

I know the tutorial describes using Gradle -> Kotlin/JS for browser route, but I decided to try out the other one 🤷‍♂️ I wasn't sure about the compiler option, so I went with IR. I then ran into trouble in chapter 7, facing this issue: https://github.com/JetBrains/kotlin-wrappers/issues/361

I couldn't really make sense of the thread, so I ended up changing the compiler back to Legacy mode. Is that the recommended solution for now? 

Not really sure what to do about this, but I thought I'd open a discussion on it since it might put some people off.

**Comment by SebastianAigner** [comment]
Hi @simonpweller and apologies for the elongated radio silence. I've since reworked the tutorials a few times (most recently today) to make sure they work with the IR compiler as well (the linked issue has also been fixed in the meantime, incidentally. Sorry if you felt lost because of the lack of guidance on the way – we'd appreciate it if you gave the tutorials another try, and welcome any other issues you might file!
